version: '3'

services:
  # MongoDB service
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - gonest-network
    volumes:
      - mongodb-data:/data/db

  # Redis service
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - gonest-network

  # Node.js API service
  nodejs-api:
    build:
      context: ./nodejs-api
    environment:
      - APP_PORT=3000
      - MONGO_DB_URI=mongodb://mongodb:27017
      - MONGO_DB_NAME=gonest-backend-api
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CACHE_TTL=60000
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - redis
    networks:
      - gonest-network

  # Go Worker service
  go-worker:
    build:
      context: ./go-worker
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - DB_NAME=gonest-backend-api
      - COLLECTION_NAME=users
      - CRON_INTERVAL=@every 5s
    depends_on:
      - mongodb
    networks:
      - gonest-network

networks:
  gonest-network:

volumes:
  mongodb-data:

