# configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: gonest-config-map
data:
  APP_PORT: "3000"
  MONGO_DB_URI: "mongodb://mongodb-service:27017"
  MONGO_DB_NAME: "gonest-backend-api"
  REDIS_HOST: "redis://redis-service:6379"
  REDIS_PORT: "6379"
  CACHE_TTL: "60000"
  MONGO_URI: "mongodb://your-mongodb-host:27017"
  DB_NAME: "gonest-backend-api"
  COLLECTION_NAME: "users"
  CRON_INTERVAL: "@every 5s"
