# go-worker-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-worker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-worker
  template:
    metadata:
      labels:
        app: go-worker
    spec:
      containers:
      - name: go-worker
        image: gonest-go-worker:v1
        envFrom:
        - configMapRef:
            name: gonest-config-map
